services:
  app:
    image: 061051226319.dkr.ecr.us-east-1.amazonaws.com/abatugo_autoscribe:0.0.9
    # image: abatugo_autoscribe:0.0.9
    platform: linux/x86-64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INPUT_DIR=/data/input
      - OUTPUT_DIR=/data/output
      - RUNNING_ENV=local  
      - CONFIG_FILE_NAME=configs.xlsx 
      - DATA_FILE_NAME=data.csv  
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output